# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-22 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_break', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateField(),
        ),
    ]
